# Generated by Django 5.2.1 on 2025-05-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=250)),
                ('expire', models.DateTimeField()),
                ('link', models.URLField(max_length=60)),
            ],
        ),
    ]
