# Generated by Django 5.2.1 on 2025-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secpath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(max_length=60, unique=True),
        ),
    ]
